mutation CreateTaskList(
  $name: String!
  $description: String
  $userId: UUID!
) @auth(level: USER) {
  taskList_insert(
    data: { name: $name, description: $description, userId: $userId }
  ) {
    id
  }
}

query GetTasksByUserId($userId: UUID!) @auth(level: USER) {
  tasks(where: { userId: { eq: $userId } }) {
    id
    title
    description
    dueDate
    isCompleted
  }
}

mutation UpdateTaskIsCompleted(
  $id: UUID!
  $isCompleted: Boolean!
) @auth(level: USER) {
  task_update(key: { id: $id }, data: { isCompleted: $isCompleted }) {
    id
  }
}

mutation DeleteTaskList($id: UUID!) @auth(level: USER) {
  taskList_delete(key: { id: $id }) {
    id
  }
}